### ISSUE TITLE
Stats presentation needs improvement - frontend

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luci/luci-py#132]
```
This bug is about changing the UI to present statistics. Issue 131 is about 
improving the statistics generated.

Let's face it, /stats is ugly and barely usable.

- It's using XHR to load the data but I'd rather get rid of this, make the data 
more useable and have copy-pastable links. Navigation is not a big deal, it's 
likely better than XHR.
- Navigating through dimension is not cute, and right now the resolutions query 
parameter is lost.
- Reordering the graph, exposing the important data to understand the system 
health at quick glance.
- I consider a good idea to present an overview (which would load quickly) 
directly at the root page. Then /stats would contain the detailed informations.

I'm giving a carte blanche to do whatever necessary to make this usable and 
informative.
```

Original issue reported on code.google.com by `maruel@chromium.org` on 6 Aug 2014 at 4:02

**Comment by kenrussell** [comment]
Please see http://crbug.com/550016 for a description of an emergency where jobs were timing out on a particular subset of the Swarming bots.

Better visibility into summary statistics is desperately needed. The question I want to answer right now is "where are the NVIDIA Retina MacBook Pros spending all their time"? To the best of my knowledge, the simplest way to answer this question is to search for tasks matching the tag "gpu:10de:0fe9" and scroll through them. Some sort of graphs are urgently needed; for example, across a subset of bots, and a time window, what percent of time was spent running what kind of test target?

I'm going to disable the majority of the tests on them, but am going to leave the two most-important (and longest-running) test suites enabled. Right now there's no easy way to know whether this is going to have much of an impact.

**Comment by maruel** [comment]
@sergeyberezin is making progress on this; he owns the monitoring/stats part.

**Comment by sergeyberezin** [comment]
http://crbug.com/408424 is the active tracking bug, and we just enabled capacity related metrics from swarming yesterday.

**Comment by techtonik** [comment]
No screenshots. Booring. :D
