### ISSUE TITLE
Python styleguide

### ISSUE THREAD

**Issue by nodirt** [luci/luci-py#220]
I'd appreciate if there was a styleguide on wiki, at least a link to an existing one with possible amendments.

In particular, I am not sure how imports should be grouped/sorted.

**Comment by maruel** [comment]
Added https://github.com/luci/luci-py/wiki/Coding-style
Note that https://codereview.appspot.com/217110043 had diverging view about subgroup spacing, which I do not mind.

**Comment by nodirt** [comment]
The doc does not say whether to

```
import Z
from X import Y
```

or

```
from X import Y
import Z
```

**Comment by maruel** [comment]
What do you prefer? Then add it to the page. I really don't care either way.

**Comment by nodirt** [comment]
Done
