### ISSUE TITLE
config component

### ISSUE THREAD

**Issue by nodirt** [luci/luci-py#223]
Implement GAE config component to read and validate configs.

```python
# myconfig.py
from google.protobuf import text_format
from components import config
from proto import mycfg_pb2

def parse_protobuf(text, type):
  msg = type()
  if text:
    text_format.Merge(text, msg)
  return msg

# Define validation rule. 
# Guarantees config.get_config() to return only valid config for my.cfg.
# Enforces storing last valid my.cfg in the datastore.
@config.validation.rule(config.self_config_set(), 'my.cfg')
def validate_mycfg(content):
  # Raising an exception in this function will mark a config as invalid
  cfg = parse_protobug(text, mycfg_pb2.MyCfg)
  assert cfg.mysetting > 0, 'My setting must be positive integer'

def get_my_cfg():
  # Due to validation rule, guaranteed to return valid configs.
  return parse_protobuf(config.get_self_config('my.cfg'), mycfg_pb2.MyCfg)
```

Use `config.ConfigApi` class to expose config api
```python
api_app = endpoints.api_server([MyApi, config.ConfigApi])
```

Will expose `validate_config` endpoint that will use rules defined by `config.validation.rule`. This will be used by config_service to validate configs and reject invalid ones on import.

**Comment by vadimsht** [comment]
If using protobuf is going to be a standard, it makes sense to add protobuf awarness too, e.g.

    @config.validation.rule(config.self_config_set(), 'my.cfg', mycfg_pb2.MyCfg)
    def validate_mycfg(msg):
      assert cfg.mysetting > 0

    def def_my_cfg():
      return config.get_self_config('my.cfg', mycfg_pb2.MyCfg)

It would also be nice to express my.cfg -> mycfg_pb2.MyCfg in single place somehow. For example:

    get_my_cfg = config.self_config('my.cfg', mycfg_pb2.MyCfg, validator=validate_mycfg):
    
    get_my_cfg().mysetting

**Comment by nodirt** [comment]
Thought of adding extra support for protobufs, but wasn't sure if we want to add a dependency.
OK, I will make sure 
1) config component will be usable without protobufs, since config service is
2) Using it with protobufs is a breeze
