### ISSUE TITLE
Auth: implement impersonation

### ISSUE THREAD

**Issue by nodirt** [luci/luci-py#227]
Implement impersonation in the auth component/service.

**Comment by shishkander** [comment]
and how is this going? :)

**Comment by vadimsht** [comment]
It isn't. What's your use case?

I don't want to rush some crap, and don't have enough time to implement non-crap now.

**Comment by shishkander** [comment]
Gerrit CQ and tryjob triggering from Gerrit. We can live with deploying GerritTryPollers, juts like RietveldTryPollers.

**Comment by nodirt** [comment]
I assume by GerritTryPoller you mean "CQ polling Gerrit issues". Not sure why you need impersonation for this.

**Comment by shishkander** [comment]
Strictly speaking, Gerrit CQ isn't blocked by this, as you've right noticed.
However, ability to trigger tryjobs from Gerrit (as Chrome extension at first) is really nice. So, my take is: this can wait for non-crappy solution.

**Comment by nodirt** [comment]
In a Chrome extension, I think the extension could get the access token from the user and talk to buildbucket on behalf of the user. Credentials should not be embedded into the extension, and I am pretty sure we will not allow credentials so widely available to have permissions to impersonate others

**Comment by shishkander** [comment]
Hm, you are right. Thanks for the heads up!

**Comment by vadimsht** [comment]
This is done in simple form that can be extended later to support more fine-grain restrictions on delegated power.
