### ISSUE TITLE
RFE: swarming: please support conditional includes in isolates

### ISSUE THREAD

**Issue by kenrussell** [luci/luci-py#230]
Currently isolates' includes can not be contained within a conditional block. Attempting to do so causes an exception in isolate.py when uploading the isolates.

It would be helpful if this feature could be supported. This would allow a popular isolate included from many places to have significantly different behavior on different platforms.

**Comment by maruel** [comment]
With the move to GN, this shouldn't become an issue anymore as GN targets can properly have conditional dependencies.

**Comment by kenrussell** [comment]
Cool. I hope Windows and Mac will move to GN soon.
