### ISSUE TITLE
auth: Group ACLs in auth_service

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-py#231]
Right now only people in 'administrators' group can view UI and manage other groups (all of them) in chrome-infra-auth.appspot.com. It's all or nothing solution. 

Ideally each group can have an owning group (e.g. project-skia-tryjob-access is managed by project-skia-admins). 

Also it might be necessary to introduce "READ" ACL for a group. For example we can make chrome-infra-auth readable by any @google.com account. Otherwise project owners will have hard time finding generic groups (e.g. "chromium-committers") that may be useful as subgroups.

(Moved from https://code.google.com/p/chromium/issues/detail?id=515563)

**Comment by maruel** [comment]
I'd rather not get too deep into this though since it can quickly become unmanageable.

**Comment by vadimsht** [comment]
For the sake of simplicity I propose to have a single global "readonly access" group. People in this group can access UI in read-only mode, and can use read-only API calls. Let's call it "auth-service-access" group. There's existing "groups-readonly-access" group, that will be deprecated by "auth-service-access".

Next, each group will also have an owning group. Owners of a group can modify the group. Owners are *not* automatically granted access to UI though (i.e. they still need to be listed in "auth-service-access" somehow). Again, it just for the sake of simplicity of implementation.

In practice we will have a large set of semi-trusted users (e.g. "*@chromium.org"), all added to "auth-service-access" group. And some structure of "owning" groups on top of it.

UI\API wise it all amounts to a new field in group definition: "Owner".

**Comment by vadimsht** [comment]
Oh, for now "Create group" action will still be limited to admins only, to be able to control a growth of number of groups.

The full use scenario is:
1) New team wants to use auth_service for something.
2) auth_service admins create 'team-name-admins' group (owned by itself), and 'team-name-members' group (owned by 'team-name-admins').
3) 'team-name-admins' carry on managing 'team-name-members' all by themselves, removing auth_service admins from the loop.

**Comment by maruel** [comment]
So effectively a tree of groups; e.g. the ACL to edit a group is implicitly defined by the group's name.

**Comment by vadimsht** [comment]
Not, implicitly. Explicitly. Each AuthGroup will have a new field in datastore: "owner = ndb.StringProperty()" with a name of owning group (or 'administrators' by default, to preserve current behavior).

Owners won't be "inherited", e.g. if "A" is owned by "B", and "B" is owned by "C", it **doesn't mean** that "A" is owned by "C" (though nothing prevents members of "C" to add "C" as subgroup to "B").

It's how Gerrit does it. It is one of saner parts of it :)

**Comment by nodirt** [comment]
nit: auth-service-readers. "access" is ambiguous: read access to write access?

**Comment by vadimsht** [comment]
"-access" to be consistent with "isolate-access". Also some members of "auth-service-access" **will** have write permissions to groups they own.

**Comment by maruel** [comment]
I think my main concern is to create a graphed presentation of the hierarchy to someone can make sense of how group relate to each others. I think it'd be good, independent of this feature request, would it be only for groups included in other groups.

**Comment by vadimsht** [comment]
This is fixed.
