### ISSUE TITLE
Support fake "Authorization" headers on devserver in Cloud Endpoints API

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-py#232]
Cloud Endpoints by default use real OAuth2 API calls to checks tokens on devserver. It is nice for manual testing (sometimes), but is very inconvenient for smoke tests.

Since components.auth wraps Cloud Endpoints auth layer completely, it is possible to replace "real" auth on dev server with fake one.

For example, Cloud Endpoints APIs on dev server can accept two kinds of Authorization headers:
1) Real ones (e.g. "Bearer <base64>"), for manual testing.
2) Fake ones: "Bearer devserver:fake@example.com".

**Comment by maruel** [comment]
swarming/local_smoke_test.py now uses the cloud endpoints API and it just works. probably not worth fixing more than that.
