### ISSUE TITLE
Simplify protocol for AuthDB replication by making it pull based

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-py#233]
I've been thinking how to implement authorization (group checks) in luci-go server/auth, so that it is 
* Simple
* Fast
* Not tied to GAE environment

I think switching from push based approach to a pull based (plus some optional change notification, e.g. via pubsub) is a simplest way to get rid of some existing bottlenecks as well as untie authDB client from GAE.

Some background on how AuthDB changes propagate now:
* auth_service has a list of service that are registered as "replicas".
* Each AuthDB change has a revision number: monotonically increasing integer.
* Whenever AuthDB changes, auth_service (via task queue) prepares `AuthDB` proto message that contains all groups and all other stuff and pushes this proto to all registered replicas via URL fetch POST call.
* It retries until all replicas acknowledge that they wrote given or some later AuthDB revision into their datastore.

There are two big limitation here:
1. URL POST is handled by frontend module on replicas and must finish within 60 sec.
2. Replicas must have HTTPS port exposed to auth_service. For example, if we want to have Commit Queue service to be AuthDB replication client, we'd have to expose it's port to outside world.

Here's proposed solution:
* auth_service has a new special group `auth-trusted-services` that lists all callers that can fetch AuthDB blobs.
* Whenever AuthDB changes, auth_service (via task queues) prepares `AuthDB` proto message and **puts it into Datastore** (in a separate entity group keyed based on AuthDB revision of the blob). It can gzip it (it should compress splendidly). Also db.Put doesn't have to be transactional since `AuthDB` snapshot at given revision is static thing.
* *[optional]* It send PubSub notification to some topic saying "hey, I have new AuthDB at revision r12345, come get it".
* Anyone in `auth-trusted-services` group at any moment can use two endpoints:
  * `GET /auth_service/authdb/revision/latest` => returns latest AuthDB revision number (just single integer)
  * `GET /auth_service/authdb/<revision>` => returns gzipped AuthDB proto message reading it straight from datastore (maybe from memcache too).
* Golang client will just put this blob into local storage (well, maybe validating it first), not bothering with unpacking it into a bunch of datastore entities.
* This blob will be loaded into local memory on all frontends to be used for authorization. (Same happens now with python clients too, essentially).

Later, when blob becomes too big, single `GET /auth_service/authdb/<revision>` can be replaced with 
`GET /auth_service/authdb/<revision>/groups` (that just lists groups) and `GET /auth_service/authdb/<revision>/groups/<name>` (that lists single group only, possibly with etag). It would allow to "copy" entire AuthDB from master to replica gradually, group by group.

**Comment by maruel** [comment]
lgtm except when returning latest, also include the digest (sha256?) of the content, so the client can assert the content is receives matches.
