### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by techtonik** [luci/luci-py#234]
Who are "The Swarming Authors" from LICENSE?

The text is pretty huge. I guess it is not MIT/BSD/CC-BY or similar because of patent fears?

**Comment by maruel** [comment]
I fixed it in 8e594074929871a9761d27e814541bc0d7d84744. The license is now coherent across the project.

**Comment by techtonik** [comment]
@maruel how did you generate it?

**Comment by maruel** [comment]
I didn't generate anything, the copyright owners are listed at https://github.com/luci/luci-py/blob/master/AUTHORS

**Comment by techtonik** [comment]
Ok. Thanks. I have a generator that is not finished yet. )
