### ISSUE TITLE
Swarming task completion PubSub notifications

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-py#235]
Currently swarming client polls for task status by periodically calling `/swarming/v1/task/<id>/result` API.

It is inconvenient when Swarming client is an appengine app. We'd like to use PubSub push notification in this case.

Outline of proposed changes:

1. Make Swarming `/swarming/v1/tasks/new` API accept `pubsub_topic` and 'pubsub_userdata` parameters. `pubsub_topic` is full PubSub topic name to send notifications to (`projects/<projectid>/topics/<topicid>`). `pubsub_userdata` is optional arbitrary blob to be added to all PubSub messages sent to the topic.
1. Make components.auth expose `<appid>.appspot.com/auth/api/v1/server/account` with service account name of the swarming service (so that clients can know what account to add to PubSub ACL). Just to avoid hardcoding service account IDs.
1. On all state changes of the swarming task, push PubSub notification to the topic. Notification includes swarming URL, task ID, `pubsub_userdata`. `pubsub_userdata` will also used as a secret string to authenticate PubSub notifications.

Open questions: how to handle duplicated tasks?

**Comment by maruel** [comment]
I think it'd be good to reply this information immediately at request time. This would save a lot of unneeded overhead with a small one off.
Otherwise, simply fire a "task completed" as the task is requested.

**Comment by erikus** [comment]
Which information at request time, the swarming URL, task ID, and userdata? I think the idea is to reuse topics for multiple tasks, but I could be wrong.

**Comment by vadimsht** [comment]
Yes, topics can (and will) be reused.

I think what M-A meant is not to bother with pubsub at all for already finished deduplicated tasks, i.e. when client posts a "new" task that already finished (e.g. exact same task ran before), server may reply right away that it is finished (instead of posting pubsub notification).

**Comment by erikus** [comment]
Makes sense, sounds good.

**Comment by maruel** [comment]
Exact.
