### ISSUE TITLE
Add client_operation_id to task request to make "tasks.new" idempotent.

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-py#237]
So if I understand the swarming code correctly, currently swarming knows how to deduplicate finished tasks. E.g. if new task A is created with properties_hash equal to already finished task B, results of task B is returned.

If A and B are created around the same time, both will run. It is bad at least in two situations:

1. DM can control pending tasks deduplication, but it needs a transactional way of adding a task.
2. Client may retry "tasks.new" call (due to network connectivity errors, for example), and accidentally create a new task.

I propose to add a lightweight mechanism for deduping task requests.

1. NewTaskRequest message grows a new optional string fields "client_operation_id".
2. There'll be new entity type ClientOperationID. Each entity in its own entity group with ID "authenticated_user_id:client_operation_id".
3. When creating new TaskRequest entity, transactionally create corresponding ClientOperationID if it doesn't exist. Return ID of existing TaskRequest stored in ClientOperationID if it already exists.

It is lightweight because it doesn't require deep changes to swarming datastore model :)

**Comment by riannucci** [comment]
I would note that 2 is particularly icky if the job (heaven forbid) has side effects. Yes, I completely 100% agree that we should try to eliminate all of the side effects, but realistically there are too many side-effects today to just allow dups :disappointed: 

(even without side effects, it's a waste of resources)

We could make ClientOperationID have entity group parents who's ID is `authenticated_user_id:HASH(client_operation_id)%SHARDS`, too, if we don't want millions of operation id roots.

**Comment by maruel** [comment]
You're concerned about spurious task because of the pubsub messages? Or about recipes that push information to a remote service? It's a risk and we'll have to cope with it in a way or another.
As for waste of resource, it's basically what we are doing at the moment. The only real saving would be from compilation PoV, but I don't feel it's worth optimizing before we have something up and running.

I'm not a fan.

**Comment by riannucci** [comment]
If swarming can't deduplicate them, then I'll need to introduce an extra mechanism on dungeon master to ensure that only one task thinks it's a given execution. I CAN do this, but it seems like it should be swarming's responsibility to do this. Does <other popular job distributor> run duplicates?

**Comment by riannucci** [comment]
Actually... I think I like that idea better anyway. We can use it to measure task-actually-started time on DM side, and use it to eliminate spurious retries in case of inopportune crashes.

**Comment by vadimsht** [comment]
okay
