### ISSUE TITLE
swarming: record & present timestamp between map and run parts of task

### ISSUE THREAD

**Issue by shishkander** [luci/luci-py#245]
The start and end of the task is already recorded and shown (e.g., [here](https://chromium-swarm.appspot.com/user/task/2c34a8f9f5f68510)). Wouldn't it be reasonable to allow differentiating between time taken to map isolates and actually run the task?

**Comment by maruel** [comment]
Yes, it's something I plan to do, it has to be surfaced from run_isolated first. I have a local branch to do this but haven't cleaned it up yet.
