### ISSUE TITLE
Make swarming bot complain when it is launched on a developer's machine from interactive session

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-py#248]
The scenario we want to avoid is developers launching the bot locally and connecting it to remote shared swarming servers (e.g. chromium-swarm-dev). It allows anyone with access to chromium-swarm-dev to run code in the context of developer workstation. It is dangerous activity (developer machine has various credentials, etc) and should be forbidden by default. It can be enabled by a flag (thus developer must acknowledge the risk by finding this flag and understanding what it means).

**Comment by maruel** [comment]
I went with whitelisted account names. It's easier to manage in a distributed fleet and the reason why the bot self-quarantine is clearly stated.
