### ISSUE TITLE
RFE: driver version in swarming_dimensions for Windows and Linux

### ISSUE THREAD

**Issue by kenrussell** [luci/luci-py#253]
During a tech talk about Chromium's GPU tests, the scenario of upgrading the graphics driver on a class of machines in the Swarming pool was discussed:
https://www.chromium.org/developers/testing/gpu-testing/gpu-bot-details#TOC-How-to-test-and-deploy-a-driver-update

This process would be quite a bit simpler if the driver version could be added to the swarming dimensions on the Windows and Linux platforms. (Mac OS only ships new graphics drivers with new OS releases.) Would this be possible?

**Comment by erikus** [comment]
+maruel

**Comment by kenrussell** [comment]
This is now urgent. We need to roll out an upgrade of the graphics driver across the Linux GPU bots in the Swarming pool, and being able to target the old vs. new driver is the responsible way of performing this rollout.

If we can spawn the executable "glxinfo" on Linux, then we can extract the driver version from the OpenGL version string using a regexp. For example, on my desktop workstation this string is:

4.5.0 NVIDIA 364.15

How long would it take to deploy this information on the Swarming pool?

**Comment by maruel** [comment]
Deploying is fast, it just needs someone to code it. I can take a look tomorrow at best.

**Comment by kenrussell** [comment]
Appreciate your picking this up.

glxinfo is provided by the mesa-utils package; I don't know the requirements on the Swarming bots, but this should be present. Spawning a separate executable should make error handling easier.

Here's the code in Chromium which extracts the driver version from the GL_VERSION string:

https://code.google.com/p/chromium/codesearch#chromium/src/gpu/config/gpu_info_collector_linux.cc&q=CollectDriverInfoGL&sq=package:chromium&type=cs&l=246

Please tell me if there are any questions about extracting or advertising it.

An exact match on the driver version is fine. It's not necessary to be able to perform inequalities on them.

**Comment by kenrussell** [comment]
Thanks for fixing this! Is the information exposed as another dimension that can be selected? I'm not seeing it in https://chromium-swarm.appspot.com/restricted/bots .

**Comment by maruel** [comment]
It is not exposed as a dimension yet, as the data would have to be processed to be normalized. It is currently visible as a state.
I just pushed it to prod now.
