### ISSUE TITLE
`client/.*cache` files seem to be left around

### ISSUE THREAD

**Issue by mithro** [luci/luci-py#259]
Currently on master I'm getting the following;
```
tansell@tansell-z620-l2:~/work/luci-py$ git status
# HEAD detached at origin/master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       client/cache/
#       client/cipd_cache/
#
nothing added to commit but untracked files present (use "git add" to track)
tansell@tansell-z620-l2:~/work/luci-py$ 
```

I'm unsure if something isn't cleaning up after itself or if these directories should be added to `.gitignore` now

**Comment by mithro** [comment]
@nodirt - I think this might be related to https://codereview.chromium.org/2069903003/ or other cipd work?

(FYI @maruel @vadimsht)

**Comment by mithro** [comment]
I uploaded https://codereview.chromium.org/2077203002/ - Dunno if that is the correct fix or not.

**Comment by nodirt** [comment]
Is it still the case 221608d40eb45409eb6cd15010b6f69d3aecf306 should have fixed it

**Comment by mithro** [comment]
I'll remove them manually and see if they come back...

**Comment by mithro** [comment]
They haven't seem to have come back.
