### ISSUE TITLE
Raspberry Pis were not quarantined when attached device was offline

### ISSUE THREAD

**Issue by rmistry** [luci/luci-py#262]
Found two instances today:
https://chromium-swarm.appspot.com/restricted/bot/skia-rpi-008
https://chromium-swarm.appspot.com/restricted/bot/skia-rpi-009

Where the attached N10s were offline but the swarming bots were still not quarantined.

Screenshot:
![skia-rpi-008](https://cloud.githubusercontent.com/assets/5244662/16265050/2e1abfbe-384b-11e6-9dc4-8caf756c791c.png)

It says "os: Android" but there is no device type and it is not quarantined.

**Comment by maruel** [comment]
@bpastene @cyberstip

**Comment by bpastene** [comment]
That's WAI I believe. @cyberstip configured android bots to always advertise as OS=Android even when all of their devices drop offline:
https://chrome-internal.googlesource.com/infra/infra_internal/+/master/services/swarming/bot_config_public.py#806

They won't be quarantined, but they won't pick up any tasks either.

**Comment by erock2112** [comment]
Any way we can make an exception for Skia?  Otherwise we have no way of knowing when our devices go offline without scanning across all Swarming bots.

**Comment by maruel** [comment]
I don't think having os:Android with no device *not* being quarantined a good idea.

**Comment by rmistry** [comment]
+1 to M-A's comment

**Comment by bpastene** [comment]
Agreed. I'll exclude skia from that behavior and also make the bots quarantine if they should have devices but don't.

**Comment by bpastene** [comment]
Fix was landed and deployed in https://chromereviews.googleplex.com/461597013/

Now an android bot will be quarantined if all its devices drop offline.
