### ISSUE TITLE
Isolate server: Inconsistent cleanup of expired items

### ISSUE THREAD

**Issue by dogben** [luci/luci-py#269]
We experienced an issue where isolate hashes that should have been valid were returning 500 errors from the isolate server. We believe the same files (with same hashes) were previously isolated but expired, and were not properly cleaned up after expiring.

From a chat with vadimsh:

for the record to investigate later https://paste.googleplex.com/5811440220897280
There was some datastore timeouts where cleaning up old items: https://isolateserver.appspot.com/restricted/ereporter2/request/5776d12600ff09908467219a560001737e69736f6c61746573657276657200016261636b656e643a323132342d3264623831396200010131
So I think they have properly expired and server was trying to remove them and did a s**** inconsistent job out of it.
but I'll have to dig into the code to verify (I thought it did the right thing...)

**Comment by vadimsht** [comment]
Yeah, there's a bug in clean cron: it doesn't check the success of "Delete datastore entry" operation.

Here: https://github.com/luci/luci-py/blob/master/appengine/isolate/model.py#L251
And here: https://github.com/luci/luci-py/blob/master/appengine/isolate/model.py#L261

Both conditions are True if the future has finished (successfully or not), as per ndb.Future docs: https://cloud.google.com/appengine/docs/python/ndb/futureclass
