### ISSUE TITLE
user/task view: add "builds with same dimensions"

### ISSUE THREAD

**Issue by shishkander** [luci/luci-py#273]
This simplifies copy-paste of request dimensions to user/tasks view and hitting search. 

I found it useful when staring at https://chromium-swarm.appspot.com/user/task/301c774472b95510 and trying to understand why it's not scheduled yet (turns out to be cpy:x86-64).

**Comment by maruel** [comment]
That's a good idea.

**Comment by kjlubick** [comment]
Something like this exists:
![h6qtgvwyug1](https://cloud.githubusercontent.com/assets/6819944/19870199/f116cb06-9f85-11e6-82f2-46460a0247db.png)
Clicking on that takes you to a list of all bots that match those dimensions.  Will that do what you want?

**Comment by maruel** [comment]
Yes. It's great, especially with the "Selected" numbers.
