### ISSUE TITLE
Repeated "Infra failure" from recipes-py should quarantine bot

### ISSUE THREAD

**Issue by dogben** [luci/luci-py#279]
The Luci recipes engine (https://github.com/luci/recipes-py) seems to distinguish between "infra failures" and a successful run with failing tests. We've seen cases where an error on a bot repeatedly causes infra failures, causing many tasks to fail due to a single bot. It would be useful if repeated infra failures could quarantine the bot (perhaps temporarily?) so that it doesn't fail all the tasks in the queue before another bot becomes available.

By contrast, we may have tests that are known to fail that should not cause bots to be quarantined.

**Comment by maruel** [comment]
Migrated to https://bugs.chromium.org/p/chromium/issues/detail?id=757932
