### ISSUE TITLE
add detailed CPU info to bot dimensions

### ISSUE THREAD

**Issue by dogben** [luci/luci-py#280]
Currently, the cpu bot dimension has values like:
cpu: x86 | x86-64
cpu: x86 | x86-64 | x86-64-avx2

It would be nice if the specific CPU could be included, similar to GPU, e.g.:
cpu: x86 | x86-64 | Intel-Core-i7-4790K-CPU-4.00GHz

The motivation is that we are scheduling Swarming tasks that run performance tests; unless the task runs on the same hardware every time, the performance results will be inconsistent. So far, we have been able to distinguish the different classes of hardware in our pool according to other dimensions, usually GPU, because we have a homogeneous hardware type for all machines with a particular GPU. However, we recently needed to add some machines with the same GPU but with a different CPU because we were not able to match the hardware exactly. It would be nice to be able to run non-performance-sensitive tasks on any of the machines, but require a specific CPU for the performance measurements.

I could imagine something slightly more generic, where we identify machines with the same hardware configuration by a hash of the CPU model, number of cores, GPU model, amount of RAM, etc. The downside of that approach is that the hash is opaque, and adding new fields in the future requires a versioning scheme.

**Comment by maruel** [comment]
The perf team uses id locking to always use the exact same worker for the tasks. This has the obvious downside of removing the ability to shard and to have resilient infrastructure. Another option is to create a very small pool (pool:Chrome-perf) that is used specifically for this.

I'm fine in theory to add this but we are constrained in the number of dimensions exposed so we need to limit the expansion for foreseeable future. :/  That said, I could probably expose this, at least for the perf bots. That said, for this to be done, someone would have to provide code to generate consistent description strings across OSes. Here's a few examples:

- build81-b1 (Windows): `Intel(R) Celeron(R) CPU N3050 @ 1.60GHz`
- build10-m3 (Ubuntu): `Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz`
- build100-b1 (OSX): `Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz`
- swarm654-c4 (Ubuntu) `Intel(R) Xeon(R) CPU @ 2.30GHz`, 

so the string cannot be used as is.

**Comment by maruel** [comment]
We can do this now!

**Comment by maruel** [comment]
Fixed in d36b5faa1ef9f51e0e0ff74363096aefb25c0962.
