### ISSUE TITLE
Retrying passed tasks shouldn't cause deduping.

### ISSUE THREAD

**Issue by mi-ac** [luci/luci-py#285]
I tried to retry a task that passed (I have reasons):
https://chromium-swarm.appspot.com/task?id=32c3f93e5ee9bd10

The retry just got deduped, but I need it to run:
https://chromium-swarm.appspot.com/task?id=32c43f1eebe8e91

I'd expect that when a user actively presses the retry button, a real retry happens.

**Comment by maruel** [comment]
Kevin, I looked at https://github.com/luci/luci-py/blob/master/appengine/swarming/ui/res/imp/taskpage/task-page.html#L777 but didn't find anything where "idempotent" would be set to true.

**Comment by maruel** [comment]
The right link for the second task is https://chromium-swarm.appspot.com/task?id=32c43f1eebe8e910

**Comment by mi-ac** [comment]
Sorry, my link was incorrect above. I cut off a digit when c/p. But the link you provided shows that it got deduped. I only see Idempotent True in the old UI in both requests.

**Comment by kjlubick** [comment]
This should be fixed on chromium-swarm

**Comment by mi-ac** [comment]
Thanks!
