### ISSUE TITLE
Swarming bot fails to report error on task

### ISSUE THREAD

**Issue by martiniss** [luci/luci-py#294]
It appears that the bot takes about an hour to complete the task, and then at the end, the task fails, and it tries to report that it failed the task. It does

`
337 2017-01-26 19:00:36.154 D: "POST /swarming/api/v1/bot/event HTTP/1.1" 401 28
`

And retries a couple times, and then gives up. This causes the task to show up as BOT_FAILED, when it really just failed the test. 

I can add more logs in a bit.

**Comment by vadimsht** [comment]
Based on server logs, this is an issue with particular bots, not Swarming server. Let's discuss it elsewhere.
