### ISSUE TITLE
how to deploy this framework for Hadoop src compile&test locally without using GAE?

### ISSUE THREAD

**Issue by suizhihao** [luci/luci-py#295]
Hello guys,  
I am an engineer from China who is doing some research on improving the efficiency of Hadoop source code's compiling and testing and I found that this dist_test framework is absolutely what I want except for the fact that it's heavily based on the GAE service which can't be used in China as we all know.

The alternatives to GAE include APPScale and TyphoonAE and so on according to my research, however, the alternative is either too new or too ancient to use.

So what I want to ask is **Is There an way which solves the demand as described in the title**?
Many Thanks in advance!!

**Comment by maruel** [comment]
The services are designed to be used on Google AppEngine, as this permits us to focus on high level services and not have to manage the security and scaling of the servers and the database. As such I recommend you to look at other continuous integration system. :/
