### ISSUE TITLE
task output is missing for longer than MIN_PACKET_INTERNAL seconds

### ISSUE THREAD

**Issue by dogben** [luci/luci-py#297]
While a task is running, the stdout of the task appears to be buffered on the bot for longer than MIN_PACKET_INTERNAL seconds, despite what the code seems to indicate here: https://github.com/luci/luci-py/blob/master/appengine/swarming/swarming_bot/bot_code/task_runner.py#L49

I don't see a bug in the code, but I tested this with several tasks that run [the attached python script](https://github.com/luci/luci-py/files/980375/test-output.py.txt). After generating output, the script sleeps 60 seconds (which should put it well beyond both MIN_PACKET_INTERNAL and MAX_PACKET_INTERVAL), then kills the bot. I ran it with several output sizes, and the output available on the server never includes all numbered lines or the line "Sleeping 60 seconds..." Example tasks:
800 lines: https://chromium-swarm.appspot.com/task?id=35f3264a58eb3b10
1600 lines: https://chromium-swarm.appspot.com/task?id=35f3267ec8fd5510
12800 lines: https://chromium-swarm.appspot.com/task?id=35f327871e646b10

Generally ~2500 bytes are missing from the end of the log.

If the bot dies or hangs while running a task, omitting the output just before it dies makes tracking down the issue very difficult.

Also, the name MIN_PACKET_INTERNAL has a typo.

**Comment by dogben** [comment]
@adrianludwin: Is this possibly related to https://codereview.chromium.org/2397083002?

(I've been suspicious that this has been a problem for a while, but I didn't try to reproduce until last week.)

**Comment by adrianludwin** [comment]
I don't recall modifying that part of the code - my changes should only have affected *how* the updates are sent out, not *when*. Do you have any reason to think it's that change?

**Comment by dogben** [comment]
No, just that I don't see any other relevant non-reverted changes.

**Comment by adrianludwin** [comment]
Ok, I'll look at this in week or so (I have some other things to deal with
first).

**Comment by maruel** [comment]
Sorry for the delay; I think this could be related to python's internal buffering.
https://github.com/luci/luci-py/blob/master/appengine/swarming/swarming_bot/bot_code/task_runner.py#L82
doesn't specify `-u`.

I will try to do a test on the staging instance to confirm if it is the issue.

**Comment by adrianludwin** [comment]
... @maruel please assign this back to me if you'd like me to take a look.

**Comment by maruel** [comment]
@dogben can you try with an explicitly call sys.stdout.flush() before the sleep. Otherwise python may cache indefinitely in-process.

**Comment by dogben** [comment]
Yes, that resolved the issue. Sorry for the noise.
